### ISSUE TITLE
Version 3.9 is not supported.

### ISSUE THREAD

**Issue by ghost** [Svenskithesource/PY4COC#1]
Please contact me: telegram - @agnostos_god; mail - tverdoy.dima.work@gmail.com

Version 3.9 is not supported.

Last file: pyiboot01_bootstrap.pyc   Traceback (most recent call last):
  File "C:\Users\katy\AppData\Local\Programs\Python\Python39\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\bin\decompile.py", line 193, in main_bin
    result = main(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\main.py", line 297, in main
    deparsed = decompile_file(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\main.py", line 208, in decompile_file
    decompile(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\main.py", line 135, in decompile
    deparsed = deparse_fn(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\semantics\pysource.py", line 2233, in code_deparse
    deparsed = walker(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\semantics\pysource.py", line 233, in __init__
    self.p = get_python_parser(
  File "c:\users\katy\desktop\python-exe-unpacker\python-decompile3\decompyle3\parsers\main.py", line 423, in get_python_parser
    raise RuntimeError(
RuntimeError: Version 3.9 is not supported.
[+] Possible entry point: pyi_rth_pkgutil.pyc

Version 3.9 is not supported.

**Comment by Cox-school** [comment]
Yep, this version uses decompyle3 which doesn't support python 3.9. Use pycdc first to decompile file.

**Comment by Svenskithesource** [comment]
I will fix this issue tonight

**Comment by Svenskithesource** [comment]
Solved
